# Generated by Django 5.0.3 on 2024-03-07 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='date',
        ),
    ]
